name: flutter_webview_pro
description: A Flutter plugin that provides a WebView widget who Support photo upload/take camera and Geolocation.
repository: https://github.com/loregr/flutter-plugins/tree/android_file_uploader/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/loregr/flutter-plugins/issues
version: 3.0.1+5

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_pro_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_pro_android: ^2.8.3+2
  webview_pro_platform_interface: ^1.8.1+2
  webview_pro_wkwebview:
    path: ../webview_flutter_wkwebview

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
